# Generated by Django 4.2.15 on 2025-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="User's name", max_length=255)),
                (
                    "work_experience",
                    models.TextField(help_text="User's work experience"),
                ),
                ("skills", models.TextField(help_text="User's skills")),
                ("education", models.TextField(help_text="User's education")),
                (
                    "certifications",
                    models.TextField(blank=True, help_text="User's certifications"),
                ),
                (
                    "other_info",
                    models.TextField(
                        blank=True, help_text="Other relevant information"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the profile was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
