# Generated by Django 5.1.5 on 2025-02-13 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user profile', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="User's name", max_length=255)),
                ('work_experience', models.TextField(help_text="User's work experience")),
                ('skills', models.TextField(help_text="User's skills")),
                ('education', models.TextField(help_text="User's education")),
                ('certifications', models.TextField(blank=True, help_text="User's certifications")),
                ('other_info', models.TextField(blank=True, help_text='Other relevant information')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
