# Generated by Django 5.1.5 on 2025-02-13 16:14

import backend.apps.job_scraping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('externalUrl', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('company_id', backend.apps.job_scraping.fields.NullableIntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('headhunterApplicationAllowed', models.BooleanField(default=False)),
                ('initialPublicationDate', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isPaid', models.BooleanField(default=False)),
                ('language_skills', models.TextField(blank=True, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('cantonCode', models.CharField(blank=True, max_length=50, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=50, null=True)),
                ('publicationDate', models.CharField(blank=True, max_length=255, null=True)),
                ('publicationEndDate', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('synonym', models.TextField(blank=True, null=True)),
                ('template_lead', models.TextField(blank=True, null=True)),
                ('template_title', models.TextField(blank=True, null=True)),
                ('industry', backend.apps.job_scraping.fields.NullableIntegerField(blank=True, null=True)),
                ('regionID', backend.apps.job_scraping.fields.NullableIntegerField(blank=True, null=True)),
                ('employmentGrades', models.TextField(blank=True, null=True)),
                ('employmentPositionIds', backend.apps.job_scraping.fields.NullableIntegerField(blank=True, null=True)),
                ('employmentTypeIds', backend.apps.job_scraping.fields.NullableIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
